// ================================================================
// DEFINITION CONTEST — IMAGE MAP
// ================================================================
//
// HOW TO USE:
//   1. Put your image files in the  image/  folder at the root.
//   2. Find the key below matching your question (SheetName_qNum).
//   3. Uncomment that line and set the filename.
//   4. Save this file — images will appear automatically.
//
// KEY FORMAT:  "SubjectKey_qNum"  →  "filename.ext"
// EXAMPLE:     "CS_3": "CS_3.png",
//
// Supported formats: .png  .jpg  .jpeg  .gif  .webp
// ================================================================

const IMAGE_MAP = {

  // ── Computer Science (CS) ──
  // CS
  // "CS_1": "CS_1.png",  // Binary number system is a base _____ system
  // "CS_2": "CS_2.png",  // The sample rate is the number of samples taken in a ___…
  // "CS_3": "CS_3.png",  // The sample resolution is the number of _____ per sample
  // "CS_4": "CS_4.png",  // Image resolution: number of _____ in an image
  // "CS_5": "CS_5.png",  // _____ is the smallest component of the image
  // "CS_6": "CS_6.png",  // 512 KiB = _____ MiB
  // "CS_7": "CS_7.png",  // Georgia compresses photographs to store them on the USB…
  // "CS_8": "CS_8.png",  // The header of a packet contains _____ IP address and __…
  // "CS_9": "CS_9.png",  // The header of a packet contains _____ number and _____ …
  // "CS_10": "CS_10.png",  // A packet contains header, _____, trailer
  // "CS_11": "CS_11.png",  // The CPU stands for Central Processing _____.
  // "CS_12": "CS_12.png",  // A printer is an example of an output _____.
  // "CS_13": "CS_13.png",  // Data entered into a computer using a keyboard is called…
  // "CS_14": "CS_14.png",  // ROM stands for Read Only _____.
  // "CS_15": "CS_15.png",  // A collection of related files is called a _____.
  // "CS_16": "CS_16.png",  // Part inside CPU, used to control the interaction of dif…
  // "CS_17": "CS_17.png",  // Which sensor measures the amount of liquid flowing thro…
  // "CS_18": "CS_18.png",  // Solid-state storage is non-_____.
  // "CS_19": "CS_19.png",  // _____ storage is used to permanently store software and…
  // "CS_20": "CS_20.png",  // A MAC address is a media _____ control address.
  // "CS_21": "CS_21.png",  // A network device has a _____ MAC address that can help …
  // "CS_22": "CS_22.png",  // An IP address is an Internet _____ address.
  // "CS_23": "CS_23.png",  // An IP address can be static or _____.
  // "CS_24": "CS_24.png",  // Which device can connect multiple devices and automatic…
  // "CS_25": "CS_25.png",  // _____ storage is a collection of servers that store dat…
  // "CS_26": "CS_26.png",  // Assembly language is an example of a _____ level langua…
  // "CS_27": "CS_27.png",  // Which level language can directly manipulate the hardwa…
  // "CS_28": "CS_28.png",  // Which level language can use specialised hardware?
  // "CS_29": "CS_29.png",  // One function of the _____ is that it has the built-in c…
  // "CS_30": "CS_30.png",  // Which translator takes one statement at a time and exec…
  // "CS_31": "CS_31.png",  // Which translator generates an error report at the end o…
  // "CS_32": "CS_32.png",  // Which programming language is written using mnemonic co…
  // "CS_33": "CS_33.png",  // Which translator makes debugging easier because each li…
  // "CS_34": "CS_34.png",  // Which translator produces fast, executable code that ru…
  // "CS_35": "CS_35.png",  // Which translator generates an error report at the end o…
  // "CS_36": "CS_36.png",  // Which translator stops the translation process as soon …
  // "CS_37": "CS_37.png",  // Once translated, which translator does not need to be p…
  // "CS_38": "CS_38.png",  // If an error is detected, which translated program will …
  // "CS_39": "CS_39.png",  // One function of a _____ is to display web pages by rend…
  // "CS_40": "CS_40.png",  // _____ cookies are stored in memory/RAM.
  // "CS_41": "CS_41.png",  // A text file sent by a web server to collect data about …
  // "CS_42": "CS_42.png",  // _____ cookies are stored on the hard drive/secondary st…
  // "CS_43": "CS_43.png",  // One function of web _____ is to send URL to DNS.
  // "CS_44": "CS_44.png",  // A _____ is one that only exists electronically.
  // "CS_45": "CS_45.png",  // The process that uses a digital ledger to track the use…

  // ── Biology (BIO) ──
  // BIO
  // "BIO_1": "BIO_1.png",  // Excretion is the removal of the waste products of _____…
  // "BIO_2": "BIO_2.png",  // A species is a group of organisms that can reproduce to…
  // "BIO_3": "BIO_3.png",  // Myriapods, insects, arachnids and crustaceans belong to…
  // "BIO_4": "BIO_4.png",  // Osmosis is the net movement of water molecules down a _…
  // "BIO_5": "BIO_5.png",  // The pressure of water inside the plant cells pressing o…
  // "BIO_6": "BIO_6.png",  // ___________ solution is used to test the presence of re…
  // "BIO_7": "BIO_7.png",  // Enzyme action involves the shape of the active site of …
  // "BIO_8": "BIO_8.png",  // At the enzyme’s ________ temperature and pH, the reacti…
  // "BIO_9": "BIO_9.png",  // ___________ is a green pigment that transfers energy fr…
  // "BIO_10": "BIO_10.png",  // The movement of nutrients from the intestines into the …
  // "BIO_11": "BIO_11.png",  // __________is the plant structure that transports sucros…
  // "BIO_12": "BIO_12.png",  // __________ is a type of white blood cell to produce ant…
  // "BIO_13": "BIO_13.png",  // __________ is the muscle contracts along with the exter…
  // "BIO_14": "BIO_14.png",  // ____________ is the molecule released and diffuses acro…
  // "BIO_15": "BIO_15.png",  // ____________ is the hormone secreted from the corpus lu…
  // "BIO_16": "BIO_16.png",  // When a herbivore sees a carnivore, which characteristic…
  // "BIO_17": "BIO_17.png",  // In a kidney tubule, which substances are filtered out o…
  // "BIO_18": "BIO_18.png",  // Which list contains only vertebrates?
  // "BIO_19": "BIO_19.png",  // Small molecules are used to synthesise large food molec…
  // "BIO_20": "BIO_20.png",  // A student used biuret reagent to test milk for the pres…
  // "BIO_21": "BIO_21.png",  // Which change occurs when areas of forest are cleared fo…
  // "BIO_22": "BIO_22.png",  // A diet contains a lot of plant material, but no meat. W…
  // "BIO_23": "BIO_23.png",  // Which two parts of the teeth are very hard?
  // "BIO_24": "BIO_24.png",  // Which blood vessel transports blood from the lungs to t…
  // "BIO_25": "BIO_25.png",  // How can the spread of disease be prevented?
  // "BIO_26": "BIO_26.png",  // What is the function of the acrosome in a sperm cell?
  // "BIO_27": "BIO_27.png",  // Which statement is a correct comparison of aerobic resp…
  // "BIO_28": "BIO_28.png",  // Which secondary sexual characteristic is associated wit…
  // "BIO_29": "BIO_29.png",  // Which statement describes transpiration?
  // "BIO_30": "BIO_30.png",  // Which characteristic is an example of continuous variat…
  // "BIO_31": "BIO_31.png",  // What is the role of mRNA?
  // "BIO_32": "BIO_32.png",  // What is the formula for calculating the magnification o…
  // "BIO_33": "BIO_33.png",  // What increases the rate of diffusion of oxygen into a c…
  // "BIO_34": "BIO_34.png",  // What are stem cells?
  // "BIO_35": "BIO_35.png",  // What is the route taken by an electrical impulse in a s…
  // "BIO_36": "BIO_36.png",  // What is the function of the iris?
  // "BIO_37": "BIO_37.png",  // A number of plants are produced using asexual reproduct…
  // "BIO_38": "BIO_38.png",  // Which structure is pollen transferred from and to durin…
  // "BIO_39": "BIO_39.png",  // Which substances are dissolved in human blood plasma?
  // "BIO_40": "BIO_40.png",  // What happens to the lining of the human uterus in the d…
  // "BIO_41": "BIO_41.png",  // What describes an allele?
  // "BIO_42": "BIO_42.png",  // What is shown by the widest block in a pyramid of numbe…
  // "BIO_43": "BIO_43.png",  // Why are bacteria useful in biotechnology and genetic mo…
  // "BIO_44": "BIO_44.png",  // Heart muscle cells have a high rate of metabolism. Whic…
  // "BIO_45": "BIO_45.png",  // What is an example of diffusion?

  // ── Business (BUS) ──
  // BUS
  // "BUS_1": "BUS_1.png",  // __________company are businesses owned by shareholders …
  // "BUS_2": "BUS_2.png",  // _________is a person who organises, operates and takes …
  // "BUS_3": "BUS_3.png",  // _______ leadership style where the manager expects to b…
  // "BUS_4": "BUS_4.png",  // _______are graphs which show how costs and revenues of …
  // "BUS_5": "BUS_5.png",  // _______outlines the responsibilities and duties to be c…
  // "BUS_6": "BUS_6.png",  // ______________is a financial plan for the marketing of …
  // "BUS_7": "BUS_7.png",  // _______occurs when people and business concentrate on w…
  // "BUS_8": "BUS_8.png",  // ____________occurs by watching a more experienced worke…
  // "BUS_9": "BUS_9.png",  // ________is an organisation of employees who have joined…
  // "BUS_10": "BUS_10.png",  // ___________is the collection and collation of original …
  // "BUS_11": "BUS_11.png",  // ____________is a term which is used to describe all the…
  // "BUS_12": "BUS_12.png",  // Added value is the difference between price and _______…
  // "BUS_13": "BUS_13.png",  // ____________are costs paid for by the rest of society, …
  // "BUS_14": "BUS_14.png",  // __________is made up of people who want to change busin…
  // "BUS_15": "BUS_15.png",  // __________is a term for those techniques used bu busine…
  // "BUS_16": "BUS_16.png",  // One of the key characteristics of successful entreprene…
  // "BUS_17": "BUS_17.png",  // All of the following are likely reasons why people work…
  // "BUS_18": "BUS_18.png",  // Which type of leadership style best defines “let it be”…
  // "BUS_19": "BUS_19.png",  // In which type of production are several identical produ…
  // "BUS_20": "BUS_20.png",  // Which one of the following products is most likely to b…
  // "BUS_21": "BUS_21.png",  // Which of the following sources of finance is most likel…
  // "BUS_22": "BUS_22.png",  // Which of the following is an example of internal financ…
  // "BUS_23": "BUS_23.png",  // A large national toy retailer wants to inform potential…
  // "BUS_24": "BUS_24.png",  // All of the following are examples of forms of informati…
  // "BUS_25": "BUS_25.png",  // Which one of the following businesses is most likely to…
  // "BUS_26": "BUS_26.png",  // XYZ Co. has found out that one of its suppliers employs…
  // "BUS_27": "BUS_27.png",  // A product sells for $7. Material and other variable cos…
  // "BUS_28": "BUS_28.png",  // Quality control in a factory is usually achieved by:
  // "BUS_29": "BUS_29.png",  // One of the external benefits resulting from a business …
  // "BUS_30": "BUS_30.png",  // One way in which businesses can contribute to sustainab…
  // "BUS_31": "BUS_31.png",  // The formula for the return on capital employed ratio (%…
  // "BUS_32": "BUS_32.png",  // The formula for the gross profit margin (%) is:
  // "BUS_33": "BUS_33.png",  // The formula for the net profit margin (%) is:
  // "BUS_34": "BUS_34.png",  // ‘The liquidity of our business is declining’. Which one…
  // "BUS_35": "BUS_35.png",  // All of the following would be found on the fixed assets…
  // "BUS_36": "BUS_36.png",  // Which of the following is a current asset?
  // "BUS_37": "BUS_37.png",  // Working capital is calculated by:
  // "BUS_38": "BUS_38.png",  // If a cashflow forecast suggests that a business will ru…
  // "BUS_39": "BUS_39.png",  // Which of the following is not a reason why a business n…
  // "BUS_40": "BUS_40.png",  // Government location grants are most likely to be made a…
  // "BUS_41": "BUS_41.png",  // The location of which one of the following businesses i…
  // "BUS_42": "BUS_42.png",  // Quality assurance means:
  // "BUS_43": "BUS_43.png",  // Which one of the following costs is most likely to be v…
  // "BUS_44": "BUS_44.png",  // The best definition of fixed costs are those that do no…
  // "BUS_45": "BUS_45.png",  // The break-even level of output is that number of units …

  // ── Art & Design (AD) ──
  // AD
  // "AD_1": "AD_1.png",  // Which color is a primary color?
  // "AD_2": "AD_2.png",  // What tool is used to erase pencil marks?
  // "AD_3": "AD_3.png",  // Which of the following is a secondary color?
  // "AD_4": "AD_4.png",  // What do we call the lightness or darkness of a color?
  // "AD_5": "AD_5.png",  // Which art material is used for watercolor painting?
  // "AD_6": "AD_6.png",  // What is a circle, square, and triangle classified as?
  // "AD_7": "AD_7.png",  // Which color is warm?
  // "AD_8": "AD_8.png",  // What do we call the way a surface feels or looks?
  // "AD_9": "AD_9.png",  // Which tool is used to hold and mix paint?
  // "AD_10": "AD_10.png",  // Which color is cool?
  // "AD_11": "AD_11.png",  // Which material is used for sculpting?
  // "AD_12": "AD_12.png",  // Which art form is three-dimensional?
  // "AD_13": "AD_13.png",  // What is a quick, rough drawing called?
  // "AD_14": "AD_14.png",  // What do we add to a color to make it lighter?
  // "AD_15": "AD_15.png",  // What do we add to a color to make it darker?
  // "AD_16": "AD_16.png",  // Which paint dries quickly and is water-based?
  // "AD_17": "AD_17.png",  // Red, yellow and blue are called the _______.
  // "AD_18": "AD_18.png",  // Which subject shows inanimate objects like fruit and fl…
  // "AD_19": "AD_19.png",  // What is art made by gluing different materials together…
  // "AD_20": "AD_20.png",  // Red, blue, and yellow are called __________ colors.
  // "AD_21": "AD_21.png",  // __________ a plastic paint that mixes with water; it is…
  // "AD_22": "AD_22.png",  // __________The element of art derived from reflected or …
  // "AD_23": "AD_23.png",  // __________ paint that needs to mix with a solvent, and …
  // "AD_24": "AD_24.png",  // A two-dimensional area with height and width is a _____…
  // "AD_25": "AD_25.png",  // __________ artworks that are three-dimensional
  // "AD_26": "AD_26.png",  // __________ paint that mixes with water
  // "AD_27": "AD_27.png",  // The lightness or darkness of a color is called_________…
  // "AD_28": "AD_28.png",  // __________ the physical volume of a shape and the space…
  // "AD_29": "AD_29.png",  // A path made by a moving point is called a__________.

  // ── Classical Chinese (CHI) ──
  // CHI
  // "CHI_1": "CHI_1.png",  // 工之侨以归……匣而埋诸土,期年出之,抱以适市。[适]
  // "CHI_2": "CHI_2.png",  // 贵人过而见之, 易之以百金, 献诸朝。[易]
  // "CHI_3": "CHI_3.png",  // 乐官传视, 皆曰:“希世之珍也。” [珍]
  // "CHI_4": "CHI_4.png",  // 盘顶如初抽笋，锐而规 [锐]
  // "CHI_5": "CHI_5.png",  // 住足不得久，乃下。[住]
  // "CHI_6": "CHI_6.png",  // 迂而僻，且无石级者，曰天门开。[僻]
  // "CHI_7": "CHI_7.png",  // 外骨，故峭石危立，望之若剑戟罴虎之林。[望]
  // "CHI_8": "CHI_8.png",  // 抚松下瞰，惊定乃笑。[惊]
  // "CHI_9": "CHI_9.png",  // 嘉靖辛卯，余闭门扫轨，朋旧少过。[轨]
  // "CHI_10": "CHI_10.png",  // 家无闲室，昼居于内，日抱小女儿以嬉。[闲]
  // "CHI_11": "CHI_11.png",  // 儿亦爱弄书，见书辄以指循行，口作声，若甚解者。[循]
  // "CHI_12": "CHI_12.png",  // 故余读常不废，时有所见，用著于录。[废]
  // "CHI_13": "CHI_13.png",  // 意到即笔，不得留，昔人所谓兔起鹘落时也。[笔]
  // "CHI_14": "CHI_14.png",  // 物之所贵于天下者，以其少有而难得也。[贵]
  // "CHI_15": "CHI_15.png",  // 故服有章，爵有等，使人不可以妄觊。[章]
  // "CHI_16": "CHI_16.png",  // 故鄗南之役，王无以为赏，乃以其爵饮将士。[饮]
  // "CHI_17": "CHI_17.png",  // 于是秦伐赵，李牧击却之。[却]
  // "CHI_18": "CHI_18.png",  // 两生雅闻其酒狂。[雅]
  // "CHI_19": "CHI_19.png",  // 今日非速君饮。[速]
  // "CHI_20": "CHI_20.png",  // 两生遽摘七经数十义叩之。[叩]
  // "CHI_21": "CHI_21.png",  // 弼索酒，被发跳叫。[被]
  // "CHI_22": "CHI_22.png",  // 今人一服儒衣，反奄奄欲绝。[服]
  // "CHI_23": "CHI_23.png",  // 录毕走送之。[走]
  // "CHI_24": "CHI_24.png",  // 余援疑质理，或遇其叱咄，色愈恭，礼愈至。[或]
  // "CHI_25": "CHI_25.png",  // 生以乡人子谒余。[谒]
  // "CHI_26": "CHI_26.png",  // 俟其欣悦，则又请焉。[俟]
  // "CHI_27": "CHI_27.png",  // 闾巷子弟执业造其家。[造]
  // "CHI_28": "CHI_28.png",  // "然独好周人急"。[周]
  // "CHI_29": "CHI_29.png",  // "人殆之，不肯舍"。[舍]
  // "CHI_30": "CHI_30.png",  // "能假我一榻乎"。[假]
  // "CHI_31": "CHI_31.png",  // "征医视脉"。[征]
  // "CHI_32": "CHI_32.png",  // "躬为煮糜炼药"。[躬]
  // "CHI_33": "CHI_33.png",  // "传其事以劝焉"。[劝]
  // "CHI_34": "CHI_34.png",  // "延就坐"。[延]
  // "CHI_35": "CHI_35.png",  // "人殆之，不肯舍"。[殆]
  // "CHI_36": "CHI_36.png",  // “未及三年”。[及]
  // "CHI_37": "CHI_37.png",  // "君之为县有惠爱"。[为]
  // "CHI_38": "CHI_38.png",  // “夫令之于民诚重矣”。[诚]
  // "CHI_39": "CHI_39.png",  // “亦被其殃而有辱也”。[被]
  // "CHI_40": "CHI_40.png",  // “固宜”。[固]
  // "CHI_41": "CHI_41.png",  // “而君则亦既去矣”。[既]
  // "CHI_42": "CHI_42.png",  // “而君则亦既去矣”。[去]
  // "CHI_43": "CHI_43.png",  // “由是好事者绘《吴山图》以为赠”。[好]
  // "CHI_44": "CHI_44.png",  // “因命余记之”。[命]
  // "CHI_45": "CHI_45.png",  // “因命余记之”。[记]

  // ── Math ──
  // MATH-0580
  // "MATH-0580_1": "MATH-0580_1.png",  // The derivative of function 𝑦=(2𝑥+1)² is _____.
  // "MATH-0580_2": "MATH-0580_2.png",  // ∫ 𝑥 𝑑𝑥 = __________.
  // "MATH-0580_3": "MATH-0580_3.png",  // The gradient of tangent × the gradient of normal is ___…
  // "MATH-0580_4": "MATH-0580_4.png",  // 𝑓²(𝑥) =(𝑓(𝑥))². (True or False)
  // "MATH-0580_5": "MATH-0580_5.png",  // Find the next term of the following sequence. 22, 17, 1…
  // "MATH-0580_6": "MATH-0580_6.png",  // For composite functions, fg(x) = gf(x) is always true. …
  // "MATH-0580_7": "MATH-0580_7.png",  // Find the gradient of the line AB, where A(3, 5) and B(4…
  // "MATH-0580_8": "MATH-0580_8.png",  // The period of the graph of 𝑦=3 sin2𝑥 +4 is _________.(i…
  // "MATH-0580_9": "MATH-0580_9.png",  // Stationary points/turning points of a function f(x) occ…
  // "MATH-0580_10": "MATH-0580_10.png",  // Only _____________ function has an inverse.
  // "MATH-0580_11": "MATH-0580_11.png",  // The gradient of 4x+2y=6 is ____________.
  // "MATH-0580_12": "MATH-0580_12.png",  // Find the mode in the following data. 1, 3, 4, 7, 3, 2, …
  // "MATH-0580_13": "MATH-0580_13.png",  // What is the expression of 3/5 as a percentage?
  // "MATH-0580_14": "MATH-0580_14.png",  // Solve the equation 3x+5=20.
  // "MATH-0580_15": "MATH-0580_15.png",  // What is the sum of interior angles of a triangle?
  // "MATH-0580_16": "MATH-0580_16.png",  // What is the area of a rectangle with length 8 and width…
  // "MATH-0580_17": "MATH-0580_17.png",  // A fair six-sided die is rolled once. What is the probab…

  // MATH-0606
  // "MATH-0606_1": "MATH-0606_1.png",  // The derivative of function 𝑦=(2𝑥+1)² is _____.
  // "MATH-0606_2": "MATH-0606_2.png",  // The magnitude of vector 3i-4j=__________.
  // "MATH-0606_3": "MATH-0606_3.png",  // The length of a unit vector is ________.
  // "MATH-0606_4": "MATH-0606_4.png",  // ∫ 𝑥 𝑑𝑥 = __________.
  // "MATH-0606_5": "MATH-0606_5.png",  // The gradient of tangent × the gradient of normal is ___…
  // "MATH-0606_6": "MATH-0606_6.png",  // The derivative of sinx is __________.
  // "MATH-0606_7": "MATH-0606_7.png",  // ∫ sin𝑥 𝑑𝑥 is __________.
  // "MATH-0606_8": "MATH-0606_8.png",  // 𝑓²(𝑥) =(𝑓(𝑥))². (True or False)
  // "MATH-0606_9": "MATH-0606_9.png",  // Find the next term of the following sequence. 22, 17, 1…
  // "MATH-0606_10": "MATH-0606_10.png",  // For composite functions, fg(x) = gf(x) is always true. …
  // "MATH-0606_11": "MATH-0606_11.png",  // Simplify e^(ln5)=_________.
  // "MATH-0606_12": "MATH-0606_12.png",  // The period of the graph of 𝑦=3 sin2𝑥 +4 is _________.(i…
  // "MATH-0606_13": "MATH-0606_13.png",  // Simplify lg2+lg5=_______.
  // "MATH-0606_14": "MATH-0606_14.png",  // sinx ∙ cosecx =_________.
  // "MATH-0606_15": "MATH-0606_15.png",  // Stationary points/turning points of a function f(x) occ…
  // "MATH-0606_16": "MATH-0606_16.png",  // In an arithmetic progression, the difference between co…
  // "MATH-0606_17": "MATH-0606_17.png",  // The 6th term of the arithmetic sequence 4, 7, 10, 13, .…
  // "MATH-0606_18": "MATH-0606_18.png",  // The 4th term of the geometric sequence 2, 6, 18, ... is…
  // "MATH-0606_19": "MATH-0606_19.png",  // The sum to infinity of the geometric series 8+4+2+1+⋯ i…
  // "MATH-0606_20": "MATH-0606_20.png",  // The second derivative is the ______ of the first deriva…
  // "MATH-0606_21": "MATH-0606_21.png",  // Which of the following is the derivative of function f …
  // "MATH-0606_22": "MATH-0606_22.png",  // The gradient of the curve 𝑦=𝑥²-3𝑥 at the point where 𝑥=…
  // "MATH-0606_23": "MATH-0606_23.png",  // The vector with A(1, 2) and B(4, 6) has components ____…
  // "MATH-0606_24": "MATH-0606_24.png",  // Simplify 𝑥² ∙ 𝑥⁴.
  // "MATH-0606_25": "MATH-0606_25.png",  // The indefinite integral of 1/x with respect to x is ___…
  // "MATH-0606_26": "MATH-0606_26.png",  // ∫₁³2𝑥𝑑𝑥=______.
  // "MATH-0606_27": "MATH-0606_27.png",  // Velocity is a _________.
  // "MATH-0606_28": "MATH-0606_28.png",  // The velocity of a particle is given by v=4t-3. Its acce…
  // "MATH-0606_29": "MATH-0606_29.png",  // The displacement of a particle is given by 𝑠=𝑡³-2𝑡²+𝑡, …
  // "MATH-0606_30": "MATH-0606_30.png",  // The set of input values is called the ___________ of th…
  // "MATH-0606_31": "MATH-0606_31.png",  // If f(x)=2x and g(x)=x+2, find fg(x).
  // "MATH-0606_32": "MATH-0606_32.png",  // The function f(x) has its inverse if and only if ______…
  // "MATH-0606_33": "MATH-0606_33.png",  // If a line is tangent to a curve, how many points of int…
  // "MATH-0606_34": "MATH-0606_34.png",  // simplify (𝑒²)³
  // "MATH-0606_35": "MATH-0606_35.png",  // log₄ 20 ÷ log₄ 5 =__________
  // "MATH-0606_36": "MATH-0606_36.png",  // Which of the following functions has a different minimu…
  // "MATH-0606_37": "MATH-0606_37.png",  // A straight line drawn from one point on the edge of a c…
  // "MATH-0606_38": "MATH-0606_38.png",  // The circle has centre O and radius 1. The length of min…
  // "MATH-0606_39": "MATH-0606_39.png",  // When the angle is measured in radians, the area of circ…
  // "MATH-0606_40": "MATH-0606_40.png",  // A reflex angle is an angle
  // "MATH-0606_41": "MATH-0606_41.png",  // -4 rad is in the _______ quadrant.
  // "MATH-0606_42": "MATH-0606_42.png",  // Which one of the following has the different value from…
  // "MATH-0606_43": "MATH-0606_43.png",  // Which of the following equations does not always equal …
  // "MATH-0606_44": "MATH-0606_44.png",  // To find the number of five digit numbers can be formed …
  // "MATH-0606_45": "MATH-0606_45.png",  // Find the range of f(x)=lnx.

  // MATH-0606-2.5
  // "MATH-0606-2.5_1": "MATH-0606-2.5_1.png",  // For composite functions, fg(x) = gf(x) always true. (Tr…
  // "MATH-0606-2.5_2": "MATH-0606-2.5_2.png",  // Simplify e^(ln5)=_________.
  // "MATH-0606-2.5_3": "MATH-0606-2.5_3.png",  // The period of the graph of 𝑦=3 sin2𝑥 +4 is _________.(i…
  // "MATH-0606-2.5_4": "MATH-0606-2.5_4.png",  // Simplify lg2+lg5=_______.
  // "MATH-0606-2.5_5": "MATH-0606-2.5_5.png",  // sinx ∙ cosecx =_________.
  // "MATH-0606-2.5_6": "MATH-0606-2.5_6.png",  // if 𝑓(𝑥)=𝑥+1, 𝑓²(𝑥)=(𝑥+1)² (True or False)
  // "MATH-0606-2.5_7": "MATH-0606-2.5_7.png",  // if 𝑓(𝑥)=𝑥+1, 𝑓⁻¹(𝑥)=1/(𝑥+1) (True or False)
  // "MATH-0606-2.5_8": "MATH-0606-2.5_8.png",  // when f(x) is divided by 2x+1, the remainder is -4. f(-0…
  // "MATH-0606-2.5_9": "MATH-0606-2.5_9.png",  // Line A and Line B are parallel, if the gradient of line…
  // "MATH-0606-2.5_10": "MATH-0606-2.5_10.png",  // Find the domain for y=lnx.
  // "MATH-0606-2.5_11": "MATH-0606-2.5_11.png",  // An obtuse angle is an angle_______
  // "MATH-0606-2.5_12": "MATH-0606-2.5_12.png",  // If the line AB has the gradient 2, and passes through t…
  // "MATH-0606-2.5_13": "MATH-0606-2.5_13.png",  // Which of the following has the smallest number of strai…
  // "MATH-0606-2.5_14": "MATH-0606-2.5_14.png",  // Which of the following functions intersects with the x-…

  // MATH-9709
  // "MATH-9709_1": "MATH-9709_1.png",  // The derivative of function 𝑦=(2𝑥+1)² is _____.
  // "MATH-9709_2": "MATH-9709_2.png",  // ∫ 𝑥 𝑑𝑥 = __________.
  // "MATH-9709_3": "MATH-9709_3.png",  // The gradient of tangent × the gradient of normal is ___…
  // "MATH-9709_4": "MATH-9709_4.png",  // 𝑓²(𝑥) =(𝑓(𝑥))². (True or False)
  // "MATH-9709_5": "MATH-9709_5.png",  // Find the next term of the following sequence. 22, 17, 1…
  // "MATH-9709_6": "MATH-9709_6.png",  // For composite functions, fg(x) = gf(x) is always true. …
  // "MATH-9709_7": "MATH-9709_7.png",  // Find the gradient of the line AB, where A(3, 5) and B(4…
  // "MATH-9709_8": "MATH-9709_8.png",  // The period of the graph of 𝑦=3 sin2𝑥 +4 is _________.(i…
  // "MATH-9709_9": "MATH-9709_9.png",  // Stationary points/turning points of a function f(x) occ…
  // "MATH-9709_10": "MATH-9709_10.png",  // Only _____________ function has an inverse.
  // "MATH-9709_11": "MATH-9709_11.png",  // -4 rad is in the _______ quadrant.
  // "MATH-9709_12": "MATH-9709_12.png",  // If two events A and B cannot occur at the same time, th…
  // "MATH-9709_13": "MATH-9709_13.png",  // Two events, A and B, are _____________ if the outcome o…
  // "MATH-9709_14": "MATH-9709_14.png",  // The most commonly occuring value is called ____________…
  // "MATH-9709_15": "MATH-9709_15.png",  // The graph of f(x) is transformed to the graph of f(x+5)…
  // "MATH-9709_16": "MATH-9709_16.png",  // The graph of f(x) is transformed to the graph of f(3x).…
  // "MATH-9709_17": "MATH-9709_17.png",  // When the gradient of a function is ____________ we say …
  // "MATH-9709_18": "MATH-9709_18.png",  // Which one is an improper integral?

  // ── EAP ──
  // EAP
  // "EAP_1": "EAP_1.png",  // The teacher ______ the documents that I submitted last …
  // "EAP_2": "EAP_2.png",  // Her British ______ made it clear that he grew up in Lon…
  // "EAP_3": "EAP_3.png",  // This region ______ wines that win international awards.
  // "EAP_4": "EAP_4.png",  // The hotel ______ breakfast that includes both local and…
  // "EAP_5": "EAP_5.png",  // The ______ where teams design robots attracts young eng…
  // "EAP_6": "EAP_6.png",  // This internship offers an ______ that enhances your car…
  // "EAP_7": "EAP_7.png",  // The manager confirmed that the room would be ______ aft…
  // "EAP_8": "EAP_8.png",  // Companies should adopt policies that reduce harm to the…
  // "EAP_9": "EAP_9.png",  // Teaching is a ______ that demands both patience and cre…
  // "EAP_10": "EAP_10.png",  // The ancient castle is ______ where three rivers meet.
  // "EAP_11": "EAP_11.png",  // Research ______ that people who read regularly sleep be…
  // "EAP_12": "EAP_12.png",  // This dress is suitable for formal ______ where etiquett…
  // "EAP_13": "EAP_13.png",  // The store offers products ______ from stationery to ele…
  // "EAP_14": "EAP_14.png",  // Her speech ______ everyone who attended the conference.
  // "EAP_15": "EAP_15.png",  // ______ checkups help detect issues that might develop i…
  // "EAP_16": "EAP_16.png",  // The team ______ solved problems that initially seemed u…
  // "EAP_17": "EAP_17.png",  // Species ______ if they adapt to environments that chang…
  // "EAP_18": "EAP_18.png",  // The cancellation ______ fans who had waited months for …
  // "EAP_19": "EAP_19.png",  // Vaccines ______ diseases that could cause widespread ou…
  // "EAP_20": "EAP_20.png",  // Climate change poses a ______ that requires global coop…
  // "EAP_21": "EAP_21.png",  // Save the document now; ______, you might lose data that…
  // "EAP_22": "EAP_22.png",  // Species ______ to climates that shift due to global war…
  // "EAP_23": "EAP_23.png",  // You've illegally ______ and misused confidential securi…
  // "EAP_24": "EAP_24.png",  // I'll call the restaurant and make a ______.
  // "EAP_25": "EAP_25.png",  // Coastal cities ______ floods that intensify with rising…
  // "EAP_26": "EAP_26.png",  // The singer has denied the magazine's ______ that she is…
  // "EAP_27": "EAP_27.png",  // The engineer who designed this system is ______ of solv…
  // "EAP_28": "EAP_28.png",  // She ______ 10% of her salary to charity every month, wh…
  // "EAP_29": "EAP_29.png",  // The store ______ that all products they sell are made f…
  // "EAP_30": "EAP_30.png",  // We must ______ resources that future generations need.
  // "EAP_31": "EAP_31.png",  // As ____ (按照要求)， this report includes a summary of stude…
  // "EAP_32": "EAP_32.png",  // To improve the overall experience, several suggestions …
  // "EAP_33": "EAP_33.png",  // Overall, the long-term benefits clearly ____________ (在…
  // "EAP_34": "EAP_34.png",  // A student _________ survey (学生满意度问卷) was distributed to…
  // "EAP_35": "EAP_35.png",  // The vast ____________ (绝大多数) of respondents expressed s…
  // "EAP_36": "EAP_36.png",  // Overall, the data from the questionnaire has ________ (…
  // "EAP_37": "EAP_37.png",  // A persuasive argumentative essay is incomplete without …
  // "EAP_38": "EAP_38.png",  // A formal report must use an ____________ (客观的) tone and…
  // "EAP_39": "EAP_39.png",  // The survey results revealed certain ____________ (方面) w…
  // "EAP_40": "EAP_40.png",  // All in ____________ (总之), the campus tour provided valu…
  // "EAP_41": "EAP_41.png",  // In ____________ (结论), the data from the questionnaire h…
  // "EAP_42": "EAP_42.png",  // After identifying the main causes of the issue, the rep…
  // "EAP_43": "EAP_43.png",  // When analyzing a short story, it is crucial to understa…
  // "EAP_44": "EAP_44.png",  // When writing a casual email to a classmate, you should …
  // "EAP_45": "EAP_45.png",  // Sarah was on ____________ (紧张不安/如坐针毡) all day, terrifie…

  // EAP-2.5
  // "EAP-2.5_1": "EAP-2.5_1.png",  // The trousers I wanted were unfortunately out of _______…
  // "EAP-2.5_2": "EAP-2.5_2.png",  // After playing football, his hair looked messy and _____…
  // "EAP-2.5_3": "EAP-2.5_3.png",  // The friendly baby had very ____________ (丰满的) cheeks.
  // "EAP-2.5_4": "EAP-2.5_4.png",  // The ____________ (有礼貌的) waiter held the door open for u…
  // "EAP-2.5_5": "EAP-2.5_5.png",  // A ____________ (可靠的) friend will never break a promise.
  // "EAP-2.5_6": "EAP-2.5_6.png",  // After the party, the ____________ (性格内向的) girl needed q…
  // "EAP-2.5_7": "EAP-2.5_7.png",  // My ____________ (节俭的) aunt reuses gift wrap to save mon…
  // "EAP-2.5_8": "EAP-2.5_8.png",  // Our ____________ (爱管闲事的) neighbor asks too many persona…
  // "EAP-2.5_9": "EAP-2.5_9.png",  // My ____________ (固执的) dog refuses to walk in the rain.
  // "EAP-2.5_10": "EAP-2.5_10.png",  // The old woman's ____________ (皱纹) showed a lifetime of …

  // ── Physics ──
  // PHY
  // "PHY_1": "PHY_1.png",  // Which property of an object never changes when a force …
  // "PHY_2": "PHY_2.png",  // Which type of radiation is measured using a detector co…
  "PHY_3": "PHY_3.png",  // The diagram represents three objects, X, Y and Z, in sp…
  // "PHY_4": "PHY_4.png",  // What is the name of the galaxy that contains our Solar …
  // "PHY_5": "PHY_5.png",  // For an object near a diverging lens, at what distance t…
  // "PHY_6": "PHY_6.png",  // Sound waves of which of the following frequencies canno…
  // "PHY_7": "PHY_7.png",  // To find the resistance of a metal wire, what measuremen…
  // "PHY_8": "PHY_8.png",  // Which of the following is NOT needed when using an appl…
  "PHY_9": "PHY_9.png",  // What phase of the moon is shown in the figure?
  // "PHY_10": "PHY_10.png",  // Which of the following energy resources cannot be trace…
  // "PHY_11": "PHY_11.png",  // What is the boiling point of water under standard atmos…
  // "PHY_12": "PHY_12.png",  // Where do visible light and microwave travel at the same…
  // "PHY_13": "PHY_13.png",  // Which quantity does a light-year measure?
  // "PHY_14": "PHY_14.png",  // In a small power station, fossil fuel is used to genera…
  // "PHY_15": "PHY_15.png",  // What cannot a radioactive source undergoing gamma decay…
  // "PHY_16": "PHY_16.png",  // A radioactive substance is used as a tracer for cancer …
  // "PHY_17": "PHY_17.png",  // Light from a distance galaxy undergoes blueshift. Which…
  // "PHY_18": "PHY_18.png",  // What does the abbreviation e.m.f. mean?
  // "PHY_19": "PHY_19.png",  // Which of the following is a scalar quantity?
  // "PHY_20": "PHY_20.png",  // Which unit is equivalent to the unit(s) of potential di…
  // "PHY_21": "PHY_21.png",  // What is the unit for the rate of energy transfer from o…
  // "PHY_22": "PHY_22.png",  // During a beta decay, where does the beta particle origi…
  // "PHY_23": "PHY_23.png",  // How does the Sun produce its energy?
  // "PHY_24": "PHY_24.png",  // Which of the following contributes the most to global w…
  // "PHY_25": "PHY_25.png",  // A force of 10 N acts on an object upwards. The object m…
  // "PHY_26": "PHY_26.png",  // Light is incident on a piece of plastic from air as sho…
  // "PHY_27": "PHY_27.png",  // Which unit is equivalent to the unit(s) of pressure?
  // "PHY_28": "PHY_28.png",  // The nearest star to the Sun is Proxima Centauri, which …
  // "PHY_29": "PHY_29.png",  // Which of the following is an SI base unit?
  // "PHY_30": "PHY_30.png",  // What is the nature of an alpha particle?
  // "PHY_31": "PHY_31.png",  // A vector quantity has ________ and ________.
  // "PHY_32": "PHY_32.png",  // Acceleration is the rate of change of ___________.
  // "PHY_33": "PHY_33.png",  // Law of reflection of wave: angle of ________ is equal t…
  // "PHY_34": "PHY_34.png",  // Hooke’s law: the _________ of the spring is proportiona…
  // "PHY_35": "PHY_35.png",  // Moment of a force is force times ______________ from pi…
  // "PHY_36": "PHY_36.png",  // Conditions for equilibrium: no net _________ and no net…
  // "PHY_37": "PHY_37.png",  // Three types of radioactive decay, alpha, _______ and __…
  // "PHY_38": "PHY_38.png",  // The closest gas giant from the Sun is ________.
  // "PHY_39": "PHY_39.png",  // ______ is the rate of flow of charge.
  // "PHY_40": "PHY_40.png",  // We use _____ hand to determine the force on a current-c…
  // "PHY_41": "PHY_41.png",  // Three ways of transferring thermal energy: conduction, …
  // "PHY_42": "PHY_42.png",  // We can hear people talking in a room with a open door w…
  // "PHY_43": "PHY_43.png",  // Scattering of _______ provides evidence for the structu…
  // "PHY_44": "PHY_44.png",  // For a __________ wave, the vibration of particles is pa…
  // "PHY_45": "PHY_45.png",  // In a solid, the movement of particles is ________.

  // PHY-2.5
  // "PHY-2.5_1": "PHY-2.5_1.png",  // A vector quantity has ________ and ________.
  // "PHY-2.5_2": "PHY-2.5_2.png",  // Acceleration is the rate of change of ___________.
  // "PHY-2.5_3": "PHY-2.5_3.png",  // Gravitational field strength is _______ per unit ______…
  // "PHY-2.5_4": "PHY-2.5_4.png",  // Hooke’s law: the _________ of the spring is proportiona…
  // "PHY-2.5_5": "PHY-2.5_5.png",  // Moment of a force is force times ___________ distance f…
  // "PHY-2.5_6": "PHY-2.5_6.png",  // Conditions for equilibrium: no net _________ and no net…
  // "PHY-2.5_7": "PHY-2.5_7.png",  // Resultant force is the rate of change of ____________.
  // "PHY-2.5_8": "PHY-2.5_8.png",  // Momentum is mass times __________.
  // "PHY-2.5_9": "PHY-2.5_9.png",  // Power is __________ per unit time.
  // "PHY-2.5_10": "PHY-2.5_10.png",  // Impulse is force times ________ for which force acts.

  // ── Chemistry ──
  // CHE
  // "CHE_1": "CHE_1.png",  // 1. _________ are atoms of the same element, that have t…
  // "CHE_2": "CHE_2.png",  // 2. _______ is formed when a pair of electrons is shared…
  // "CHE_3": "CHE_3.png",  // 3._______is the electrostatic attraction between the po…
  // "CHE_4": "CHE_4.png",  // 4.The _______ as the molten or aqueous substance that u…
  // "CHE_5": "CHE_5.png",  // 5.Colour of methyl orange in alkaline solution is _____…
  // "CHE_6": "CHE_6.png",  // 6. The transfer of thermal energy during a reaction is …
  // "CHE_7": "CHE_7.png",  // 7. A strong acid _________ dissociate in aqueous soluti…
  // "CHE_8": "CHE_8.png",  // 8. ZnO is an example of ______ oxides
  // "CHE_9": "CHE_9.png",  // 9. Group VII elements in the periodic table are known a…
  // "CHE_10": "CHE_10.png",  // 10. ___________is a substance that oxidises another sub…
  // "CHE_11": "CHE_11.png",  // 11. __________ is a compound containing only carbon and…
  // "CHE_12": "CHE_12.png",  // 12. Polymers as large molecules built up from many smal…
  // "CHE_13": "CHE_13.png",  // 13. _________ are compounds with the same molecular for…
  // "CHE_14": "CHE_14.png",  // 14. In an _______ reaction, only one product is formed
  // "CHE_15": "CHE_15.png",  // 15. _________ solution as a solution containing the max…
  // "CHE_16": "CHE_16.png",  // 1. Relative atomic mass is the average mass of the ____…
  // "CHE_17": "CHE_17.png",  // 2. The _________ is the process for making ammonia unde…
  // "CHE_18": "CHE_18.png",  // 3. What is the Avogadro constant?
  // "CHE_19": "CHE_19.png",  // 4. What is the change of physical state from solid to g…
  // "CHE_20": "CHE_20.png",  // 5. The mass number/nucleon number is the total number o…
  // "CHE_21": "CHE_21.png",  // 6. Define the _____ formula of a compound as the simple…
  // "CHE_22": "CHE_22.png",  // 7. An endothermic reaction ______ thermal energy leadin…
  // "CHE_23": "CHE_23.png",  // 8. Oxidation is: ______ of electrons and; _______ in ox…
  // "CHE_24": "CHE_24.png",  // 9. A reducing agent is a substance that ____ another su…
  // "CHE_25": "CHE_25.png",  // 10. Acids are proton _____ and bases are proton _____
  // "CHE_26": "CHE_26.png",  // 11. Aluminium oxide is a/an _______ oxides
  // "CHE_27": "CHE_27.png",  // 12. Group _______ atoms have a full outer electron shel…
  // "CHE_28": "CHE_28.png",  // 13. the number of occupied electron shells is equal to …
  // "CHE_29": "CHE_29.png",  // 14. simple molecular compounds have ______ melting poin…
  // "CHE_30": "CHE_30.png",  // 15. a hydrogen–oxygen fuel cell uses hydrogen and oxyge…
  // "CHE_31": "CHE_31.png",  // 16. activation energy, Ea, as the ______ energy that co…
  // "CHE_32": "CHE_32.png",  // 17. a catalyst ______ the rate of a reaction and is ___…
  // "CHE_33": "CHE_33.png",  // 18. chlorides are soluble, except and silver
  // "CHE_34": "CHE_34.png",  // 19. a hydrated substance as a substance that is _______…
  // "CHE_35": "CHE_35.png",  // 20. Group I alkali metals have ______ melting point, an…
  // "CHE_36": "CHE_36.png",  // 21. chlorine is a _______ gas
  // "CHE_37": "CHE_37.png",  // 22. the main ore of aluminium is _______ and that alumi…
  // "CHE_38": "CHE_38.png",  // 23. the treatment of the domestic water supply uses ___…
  // "CHE_39": "CHE_39.png",  // 24. Members of a homologous series have the ______ gene…
  // "CHE_40": "CHE_40.png",  // 25. the separation of petroleum into useful fractions i…
  // "CHE_41": "CHE_41.png",  // 26. The _______ fraction of petroleum is used as a chem…
  // "CHE_42": "CHE_42.png",  // 27. In a ________ reaction one atom or group of atoms i…
  // "CHE_43": "CHE_43.png",  // 28. alkenes can be manufactured by the _______ of large…
  // "CHE_44": "CHE_44.png",  // 29. the ethanoic acid can be formed by the oxidation of…
  // "CHE_45": "CHE_45.png",  // 30. Proteins are natural _______ that are formed from a…

  // CHE-2.5
  // "CHE-2.5_1": "CHE-2.5_1.png",  // 1. _________ are atoms of the same element, that have t…
  // "CHE-2.5_2": "CHE-2.5_2.png",  // 2. _______ is formed when a pair of electrons is shared…
  // "CHE-2.5_3": "CHE-2.5_3.png",  // 3._______is the electrostatic attraction between the po…
  // "CHE-2.5_4": "CHE-2.5_4.png",  // 4.The _______ as the molten or aqueous substance that u…
  // "CHE-2.5_5": "CHE-2.5_5.png",  // 5.Colour of methyl orange in alkaline solution is _____…
  // "CHE-2.5_6": "CHE-2.5_6.png",  // 6. The transfer of thermal energy during a reaction is …
  // "CHE-2.5_7": "CHE-2.5_7.png",  // 7. A strong acid _________ dissociate in aqueous soluti…
  // "CHE-2.5_8": "CHE-2.5_8.png",  // 8. a reversible reaction in a _____ system is at equili…
  // "CHE-2.5_9": "CHE-2.5_9.png",  // 9. the sum of the oxidation numbers in a compound is __…
  // "CHE-2.5_10": "CHE-2.5_10.png",  // 10. ___________is a substance that oxidises another sub…

  // ── Economics ──
  // ECON
  // "ECON_1": "ECON_1.png",  // __________ means limited resources cannot satisfy unlim…
  // "ECON_2": "ECON_2.png",  // Opportunity cost is the ________________ alternative/ch…
  // "ECON_3": "ECON_3.png",  // ______ good is man-made resource used to produce other …
  // "ECON_4": "ECON_4.png",  // __________ is the willingness and ability to organize r…
  // "ECON_5": "ECON_5.png",  // Free goods are goods that are unlimited in supply, do n…
  // "ECON_6": "ECON_6.png",  // Social cost is the sum of private cost and _________ co…
  // "ECON_7": "ECON_7.png",  // ________ income is the income left after deduction of i…
  // "ECON_8": "ECON_8.png",  // A product is a _________ when its purchase can replace …
  // "ECON_9": "ECON_9.png",  // ________ is a payment provided by government to produce…
  // "ECON_10": "ECON_10.png",  // Market ________ is achieved when market demand equals m…
  // "ECON_11": "ECON_11.png",  // Demand is price elastic wen PED is greater than _______…
  // "ECON_12": "ECON_12.png",  // Supply is price ________ when percentage change in pric…
  // "ECON_13": "ECON_13.png",  // __________ measures the amount of output produced by pe…
  // "ECON_14": "ECON_14.png",  // _______ cost do not vary with the level of output, it e…
  // "ECON_15": "ECON_15.png",  // ________ sector is about the production or extraction o…
  // "ECON_16": "ECON_16.png",  // What is the cause of economic scarcity?
  // "ECON_17": "ECON_17.png",  // What is a factor of production?
  "ECON_18": "ECON_18.png",  // Which diagram shows an opportunity cost by movement fro…
  // "ECON_19": "ECON_19.png",  // What will result in a movement along the demand curve f…
  // "ECON_20": "ECON_20.png",  // What is the most likely cause of a product having a pri…
  "ECON_21": "ECON_21.png",  // In the diagram, which supply curve has the perfectly in…
  // "ECON_22": "ECON_22.png",  // What is a disadvantage of a market economy?
  // "ECON_23": "ECON_23.png",  // What is an example of a public good?
  // "ECON_24": "ECON_24.png",  // What would be least likely to act as a store of value d…
  // "ECON_25": "ECON_25.png",  // The use of a mobile phone to make payments is an exampl…
  // "ECON_26": "ECON_26.png",  // Which type of economy of scale results from a firm prod…
  // "ECON_27": "ECON_27.png",  // Which measure would indicate that an expansionary fisca…
  // "ECON_28": "ECON_28.png",  // What is an expansionary monetary policy?
  // "ECON_29": "ECON_29.png",  // What may directly cause economic growth?
  "ECON_30": "ECON_30.png",  // The table shows economic indicators for an economy over…
  // "ECON_31": "ECON_31.png",  // A person receives annual interest of 4% on their saving…
  // "ECON_32": "ECON_32.png",  // Real Gross Domestic Product (GDP) per capita is a bette…
  // "ECON_33": "ECON_33.png",  // If the rate of inflation rises from 2% to 10%, which fu…
  "ECON_34": "ECON_34.png",  // If interest rates fall, what will be the most likely ef…
  // "ECON_35": "ECON_35.png",  // What three key questions determine resource allocation?
  "ECON_36": "ECON_36.png",  // Which factor has the correct factor reward identified?
  "ECON_37": "ECON_37.png",  // The supply of which good is likely to be most price ela…
  "ECON_38": "ECON_38.png",  // In the diagram, which demand curve has perfectly elasti…
  // "ECON_39": "ECON_39.png",  // A clothing manufacturer expands by taking over a clothi…
  // "ECON_40": "ECON_40.png",  // A shop worker was made redundant due to the introductio…
  "ECON_41": "ECON_41.png",  // The diagram shows a firm’s total cost (TC) curve.What i…
  // "ECON_42": "ECON_42.png",  // What is an example of a free good?
  "ECON_43": "ECON_43.png" // The diagram shows a production possibility curve (PPC).…
  // "ECON_44": "ECON_44.png",  // What is defined as ‘a reduction in gross domestic produ…
  // "ECON_45": "ECON_45.png",  // Which activity takes place in the tertiary sector?

  // ECON-2.5
  // "ECON-2.5_1": "ECON-2.5_1.png",  // __________ means limited resources cannot satisfy unlim…
  // "ECON-2.5_2": "ECON-2.5_2.png",  // Opportunity cost is the ________________ alternative/ch…
  // "ECON-2.5_3": "ECON-2.5_3.png",  // ______ good is man-made resource used to produce other …
  // "ECON-2.5_4": "ECON-2.5_4.png",  // __________ is the willingness and ability to organize r…
  // "ECON-2.5_5": "ECON-2.5_5.png",  // Free goods are goods that are unlimited in supply, do n…
  // "ECON-2.5_6": "ECON-2.5_6.png",  // Social cost is the sum of private cost and _________ co…
  // "ECON-2.5_7": "ECON-2.5_7.png",  // ________ income is the income left after deduction of i…
  // "ECON-2.5_8": "ECON-2.5_8.png",  // A product is a _________ when its purchase can replace …
  // "ECON-2.5_9": "ECON-2.5_9.png",  // ________ is a payment provided by government to produce…
  // "ECON-2.5_10": "ECON-2.5_10.png",  // Market ________ is achieved when market demand equals m…

};
